layout_spectrum: 0.7343919058330357
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.9226805788930506
  brandStrength: 0.5053763
  lightness: 0.7313293328043073
  brandColors:
    - '#31322A'
    - '#EBECF1'
    - '#555651'
    - '#B3B3B3'
    - '#828280'
  rhythmicContrast: 0.913468575803563
typography_spectrum: 0.2133417008444667
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Artman
