name: Artman
favicon: null
layout_spectrum: 0.7343919058330357
typography_spectrum: 0.2133417008444667
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5983854685910046
  lightness: 0.7313293328043073
  saturation: 0.9226805788930506
  rhythmicContrast: 0.913468575803563
purpose: []
